/**
 * This file is auto-generated by `pnpm supabase:types`.
 *
 * Do not edit by hand. Regenerate after every migration.
 *
 * Placeholder content below; running `pnpm supabase:types` against a real
 * Supabase project will overwrite this with the full schema typing.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: Record<string, { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> }>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
